/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import DAO.FornecedorDao;
import entidades.Fornecedor;
import java.util.List;
import model.FornecedorListModel;

/**
 *
 * @author Gusta
 */
public class FormularioBuscarFornecedor extends javax.swing.JInternalFrame {

    FornecedorDao fornecedorDao = new FornecedorDao();
    FornecedorListModel fornecedorListModel;

    /**
     * Creates new form FormularioBuscarClientes
     */
    public FormularioBuscarFornecedor() {
        initComponents();
        List<Fornecedor> lista = fornecedorDao.listar();
        fornecedorListModel = new FornecedorListModel(lista);
        tabelaFornecedores.setModel(fornecedorListModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNome = new javax.swing.JLabel();
        jtBuscarFornecedor = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFornecedores = new javax.swing.JTable();
        btEditar = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jNome.setText("Nome:");

        jtBuscarFornecedor.setColumns(20);

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        tabelaFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "E-mail", "Telefone", "Rua", "Número", "Bairro", "Cidade", "Estado", "CNPJ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaFornecedores);

        btEditar.setText("Editar Fornecedor");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btRemover.setText("Remover Fornecedor");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        btAtualizar.setText("Atualizar Tabela");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jNome)
                        .addGap(18, 18, 18)
                        .addComponent(jtBuscarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btBuscar)
                        .addGap(71, 71, 71)
                        .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btEditar)
                .addGap(18, 18, 18)
                .addComponent(btRemover)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNome)
                    .addComponent(jtBuscarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar)
                    .addComponent(btAtualizar))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEditar)
                    .addComponent(btRemover))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        List<Fornecedor> lista;
        lista = fornecedorDao.buscarPorNome(jtBuscarFornecedor.getText());
        fornecedorListModel = new FornecedorListModel(lista);
        tabelaFornecedores.setModel(fornecedorListModel);
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        int indiceTabela = tabelaFornecedores.getSelectedRow();
        int fornecedorID = (Integer) fornecedorListModel.getValueAt(indiceTabela, 0);
        String nome = (String) fornecedorListModel.getValueAt(indiceTabela, 1);
        String email = (String) fornecedorListModel.getValueAt(indiceTabela, 2);
        String telefone = (String) fornecedorListModel.getValueAt(indiceTabela, 3);
        String rua = (String) fornecedorListModel.getValueAt(indiceTabela, 4);
        String numero = (String) fornecedorListModel.getValueAt(indiceTabela, 5);
        String bairro = (String) fornecedorListModel.getValueAt(indiceTabela, 6);
        String cidade = (String) fornecedorListModel.getValueAt(indiceTabela, 7);
        String estado = (String) fornecedorListModel.getValueAt(indiceTabela, 8);
        String cnpj = (String) fornecedorListModel.getValueAt(indiceTabela, 9);

        Fornecedor fornecedor = new Fornecedor();
        fornecedor.setFornecedorID(fornecedorID);
        fornecedor.setNome(nome);
        fornecedor.setEmail(email);
        fornecedor.setTelefone(telefone);
        fornecedor.setRua(rua);
        fornecedor.setNumero(numero);
        fornecedor.setBairro(bairro);
        fornecedor.setCidade(cidade);
        fornecedor.setEstado(estado);
        fornecedor.setCnpj(cnpj);

        FormularioEditarFornecedor formFornecedor = new FormularioEditarFornecedor(fornecedor);
        formFornecedor.setDados(fornecedor);
        getParent().add(formFornecedor);
        formFornecedor.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_btEditarActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        int indiceTabela = tabelaFornecedores.getSelectedRow();
        Object idFornecedor = fornecedorListModel.getValueAt(indiceTabela, 0);
        fornecedorDao.remover((Integer) idFornecedor);
        fornecedorListModel.removeModel(indiceTabela);
    }//GEN-LAST:event_btRemoverActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        List<Fornecedor> lista = fornecedorDao.listar();
        fornecedorListModel = new FornecedorListModel(lista);
        tabelaFornecedores.setModel(fornecedorListModel);
    }//GEN-LAST:event_btAtualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btRemover;
    private javax.swing.JLabel jNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtBuscarFornecedor;
    private javax.swing.JTable tabelaFornecedores;
    // End of variables declaration//GEN-END:variables
}
