/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import DAO.ClienteDao;
import entidades.Cliente;

import javax.swing.JOptionPane;

/**
 *
 * @author Gusta
 */
public class FormularioEditarCliente extends javax.swing.JInternalFrame {

    Cliente cliente;

    public FormularioEditarCliente(Cliente cliente) {
        initComponents();
        this.cliente = cliente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCNome1 = new javax.swing.JLabel();
        txtNome1 = new javax.swing.JTextField();
        txtDtNasc1 = new javax.swing.JTextField();
        jEditarCliente1 = new javax.swing.JButton();
        jCTelefone1 = new javax.swing.JLabel();
        jCRg1 = new javax.swing.JLabel();
        txtEstado1 = new javax.swing.JTextField();
        jCRua1 = new javax.swing.JLabel();
        jCDadosPessoais1 = new javax.swing.JLabel();
        jCCpf1 = new javax.swing.JLabel();
        txtRG1 = new javax.swing.JTextField();
        jCNumero1 = new javax.swing.JLabel();
        jCEmail1 = new javax.swing.JLabel();
        txtTelefone1 = new javax.swing.JTextField();
        txtRua1 = new javax.swing.JTextField();
        jCDataNasc1 = new javax.swing.JLabel();
        txtNumero1 = new javax.swing.JTextField();
        txtEmail1 = new javax.swing.JTextField();
        txtCidade1 = new javax.swing.JTextField();
        txtBairro1 = new javax.swing.JTextField();
        jCEndereco1 = new javax.swing.JLabel();
        jCEstado1 = new javax.swing.JLabel();
        jCBairro1 = new javax.swing.JLabel();
        jCCidade1 = new javax.swing.JLabel();
        txtCPF1 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Clientes");
        setAlignmentX(2.0F);
        setFont(new java.awt.Font("Impact", 0, 10)); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 300));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        jCNome1.setText("Nome:");

        txtDtNasc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDtNasc1ActionPerformed(evt);
            }
        });

        jEditarCliente1.setText("Salvar Edição");
        jEditarCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditarCliente1ActionPerformed(evt);
            }
        });

        jCTelefone1.setText("Telefone:");

        jCRg1.setText("RG:");

        txtEstado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstado1ActionPerformed(evt);
            }
        });

        jCRua1.setText("Rua:");

        jCDadosPessoais1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCDadosPessoais1.setText("Dados Pessoais");

        jCCpf1.setText("CPF:");

        jCNumero1.setText("Número:");

        jCEmail1.setText("E-mail:");

        txtTelefone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefone1ActionPerformed(evt);
            }
        });

        jCDataNasc1.setText("Data de Nasc:");

        txtCidade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidade1ActionPerformed(evt);
            }
        });

        jCEndereco1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCEndereco1.setText("Endereço");

        jCEstado1.setText("Estado:");

        jCBairro1.setText("Bairro:");

        jCCidade1.setText("Cidade:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCCidade1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCEstado1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEstado1)
                        .addGap(236, 236, 236)
                        .addComponent(jEditarCliente1)
                        .addGap(76, 76, 76))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCDadosPessoais1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCTelefone1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCNome1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCDataNasc1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDtNasc1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCCpf1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCPF1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCRg1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtRG1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jCEmail1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jCRua1)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtRua1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addComponent(jCNumero1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jCBairro1)
                            .addGap(18, 18, 18)
                            .addComponent(txtBairro1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jCEndereco1))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jCDadosPessoais1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCNome1)
                    .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCDataNasc1)
                    .addComponent(jCCpf1)
                    .addComponent(txtCPF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCRg1)
                    .addComponent(txtRG1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDtNasc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCTelefone1)
                    .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCEmail1))
                .addGap(12, 12, 12)
                .addComponent(jCEndereco1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCRua1)
                    .addComponent(txtRua1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCNumero1)
                    .addComponent(txtNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBairro1)
                    .addComponent(txtBairro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEditarCliente1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCCidade1)
                        .addComponent(txtCidade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCEstado1)
                        .addComponent(txtEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDtNasc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDtNasc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDtNasc1ActionPerformed

    private void jEditarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditarCliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEditarCliente1ActionPerformed

    private void txtEstado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstado1ActionPerformed

    private void txtTelefone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefone1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefone1ActionPerformed

    private void txtCidade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidade1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidade1ActionPerformed

    private boolean validarCampos() {
        // Verificando se os campos estão preenchidos
        if (txtNome1.getText().isEmpty()
                || txtDtNasc1.getText().isEmpty()
                || txtCPF1.getText().isEmpty()
                || txtRG1.getText().isEmpty()
                || txtRua1.getText().isEmpty()
                || txtNumero1.getText().isEmpty()
                || txtEstado1.getText().isEmpty()
                || txtCidade1.getText().isEmpty()
                || txtBairro1.getText().isEmpty()
                || txtTelefone1.getText().isEmpty()
                || txtEmail1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Realizando outras validações se necessário
        return true;
    }

    private void editarCliente() {
        // Criando um objeto Cliente com os dados do formulário
        ClienteDao clienteDao = new ClienteDao();
        cliente.setNome(txtNome1.getText());
        cliente.setDataNascimento(txtDtNasc1.getText());
        cliente.setCpf(txtCPF1.getText());
        cliente.setRg(txtRG1.getText());
        cliente.setRua(txtRua1.getText());
        cliente.setNumero(txtNumero1.getText());
        cliente.setEstado(txtEstado1.getText());
        cliente.setCidade(txtCidade1.getText());
        cliente.setBairro(txtBairro1.getText());
        cliente.setTelefone(txtTelefone1.getText());
        cliente.setEmail(txtEmail1.getText());

        // Salvando o cliente no banco de dados
        clienteDao.alterar(cliente);
        JOptionPane.showMessageDialog(this, "Cliente editado com sucesso!", "Editar", JOptionPane.INFORMATION_MESSAGE);

        // Limpando os campos do formulário
        limparCampos();
    }

    private void limparCampos() {
        txtNome1.setText("");
        txtDtNasc1.setText("");
        txtCPF1.setText("");
        txtRG1.setText("");
        txtRua1.setText("");
        txtNumero1.setText("");
        txtEstado1.setText("");
        txtCidade1.setText("");
        txtBairro1.setText("");
        txtTelefone1.setText("");
        txtEmail1.setText("");
    }

    public void setDados(Cliente cliente) {
        txtNome1.setText(cliente.getNome());
        txtDtNasc1.setText(cliente.getDataNascimento());
        txtCPF1.setText(cliente.getCpf());
        txtRG1.setText(cliente.getRg());
        txtRua1.setText(cliente.getRua());
        txtNumero1.setText(cliente.getNumero());
        txtEstado1.setText(cliente.getEstado());
        txtCidade1.setText(cliente.getCidade());
        txtBairro1.setText(cliente.getBairro());
        txtTelefone1.setText(cliente.getTelefone());
        txtEmail1.setText(cliente.getEmail());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jCBairro1;
    private javax.swing.JLabel jCCidade1;
    private javax.swing.JLabel jCCpf1;
    private javax.swing.JLabel jCDadosPessoais1;
    private javax.swing.JLabel jCDataNasc1;
    private javax.swing.JLabel jCEmail1;
    private javax.swing.JLabel jCEndereco1;
    private javax.swing.JLabel jCEstado1;
    private javax.swing.JLabel jCNome1;
    private javax.swing.JLabel jCNumero1;
    private javax.swing.JLabel jCRg1;
    private javax.swing.JLabel jCRua1;
    private javax.swing.JLabel jCTelefone1;
    private javax.swing.JButton jEditarCliente1;
    private javax.swing.JTextField txtBairro1;
    private javax.swing.JTextField txtCPF1;
    private javax.swing.JTextField txtCidade1;
    private javax.swing.JTextField txtDtNasc1;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtEstado1;
    private javax.swing.JTextField txtNome1;
    private javax.swing.JTextField txtNumero1;
    private javax.swing.JTextField txtRG1;
    private javax.swing.JTextField txtRua1;
    private javax.swing.JTextField txtTelefone1;
    // End of variables declaration//GEN-END:variables

}
