/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import DAO.ClienteDao;
import DAO.ProdutoDao;
import DAO.VendaDao;
import entidades.Cliente;
import entidades.Produto;
import entidades.Venda;
import model.ProdutoListModel;
import model.VendaListModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Gusta
 */
public class FormularioVendas extends javax.swing.JInternalFrame {

    ProdutoDao produtoDao = new ProdutoDao();
    ClienteDao clienteDao = new ClienteDao();
    List<Venda> listaVenda = new ArrayList<Venda>();
    VendaListModel vendaListModel = new VendaListModel(listaVenda);
    ProdutoListModel produtoListModel;
    VendaDao vendaDao = new VendaDao();

    public FormularioVendas() {
        initComponents();
        List<Produto> lista = produtoDao.listar();
        produtoListModel = new ProdutoListModel(lista);
        tabelaProdutos2.setModel(produtoListModel);

        List<Cliente> listaClientes = clienteDao.listar();
        for (Cliente cliente : listaClientes) {
            int item;
            item = cliente.getClienteID();
            jComboCliente.addItem(String.valueOf(item));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCarrinho = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        jComboProduto = new javax.swing.JComboBox<>();
        btBuscar = new javax.swing.JButton();
        jTbusca = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaVendas = new javax.swing.JTable();
        jCliente = new javax.swing.JLabel();
        jComboCliente = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaProdutos2 = new javax.swing.JTable();
        jListaCompras = new javax.swing.JLabel();
        btVenda = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        btCarrinho.setText("Vender");
        btCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCarrinhoActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        jComboProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Nome" }));

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        jTbusca.setColumns(20);

        tabelaVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cliente", "Produto", "Quantidade", "Valor Pago"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaVendas);

        jCliente.setText("Cliente:");

        jComboCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboClienteActionPerformed(evt);
            }
        });

        tabelaProdutos2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Categoria", "Quantidade", "Valor de Custo", "Valor de Venda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tabelaProdutos2);

        jListaCompras.setText("Lista de compras");

        btVenda.setText("Abrir recibo");
        btVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jComboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTbusca, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btBuscar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btLimpar))
                                .addComponent(jListaCompras)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jCliente)
                                    .addGap(18, 18, 18)
                                    .addComponent(jComboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btCarrinho)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btVenda)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar)
                    .addComponent(btLimpar)
                    .addComponent(jTbusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCliente)
                    .addComponent(btCarrinho))
                .addGap(12, 12, 12)
                .addComponent(jListaCompras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btVenda)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCarrinhoActionPerformed
        int quantidadeVendida = Integer.parseInt(JOptionPane.showInputDialog("Quantidade: "));

        String clienteSelecionado = jComboCliente.getSelectedItem().toString();
       int codigoCliente = 0;
if (!clienteSelecionado.isEmpty()) {
    try {
        codigoCliente = Integer.parseInt(clienteSelecionado);
    } catch (NumberFormatException e) {
        System.out.println("O valor selecionado não é um número válido para o código do cliente.");
        e.printStackTrace();
    }
}

        int indiceTabelaProduto = tabelaProdutos2.getSelectedRow();
        Object valorProduto = produtoListModel.getValueAt(indiceTabelaProduto, 0);
        int codigoProduto = (valorProduto != null) ? Integer.parseInt(valorProduto.toString()) : 0;
        int qtdeProduto = (Integer) produtoListModel.getValueAt(indiceTabelaProduto, 3);
        double precoProduto = (Double) produtoListModel.getValueAt(indiceTabelaProduto, 5);

        ProdutoDao prodDao = new ProdutoDao();
        Produto produto = prodDao.buscarPorCodigo(codigoProduto);

        ClienteDao clienteDao = new ClienteDao();
        Cliente cliente = clienteDao.buscarPorCodigo(codigoCliente);

        Venda venda = new Venda();
        venda.setCliente(cliente);
        venda.setProduto(produto);
        venda.setQuantidade(quantidadeVendida);
        venda.setValorVenda(precoProduto * quantidadeVendida);

// Salva novo estoque
        produto.setQuantidade(qtdeProduto - quantidadeVendida);
        prodDao.alterar(produto);

// concretiza a venda
        vendaDao.inserirVenda(venda);

// evento de GUI (Jtable)
        vendaListModel.insertModel(venda);
        tabelaVendas.setModel(vendaListModel);

    }//GEN-LAST:event_btCarrinhoActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        btLimpar.setText("");
        List<Produto> lista = produtoDao.listar();
        produtoListModel = new ProdutoListModel(lista);
        tabelaProdutos2.setModel(produtoListModel);
    }//GEN-LAST:event_btLimparActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        List<Produto> lista = new ArrayList<>();
        if (jComboProduto.getSelectedItem() == "Nome") {
            lista = produtoDao.buscarPorNome(jTbusca.getText());
        } else {
            lista.add(produtoDao.buscarPorCodigo(Integer.parseInt(jTbusca.getText())));
        }

        produtoListModel = new ProdutoListModel(lista);
        tabelaProdutos2.setModel(produtoListModel);
    }//GEN-LAST:event_btBuscarActionPerformed

    private void jComboClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboClienteActionPerformed

    private void btVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVendaActionPerformed
        List<Venda> venda = new ArrayList<>();
        int totalRows = tabelaVendas.getRowCount();

        for (int i = 0; i < totalRows; i++) {
            Venda v = new Venda();
            v.setClienteID((int) tabelaVendas.getModel().getValueAt(i, 0));
            v.setProdutoID((int) tabelaVendas.getModel().getValueAt(i, 1));
            v.setQuantidade((int) tabelaVendas.getModel().getValueAt(i, 2));
            v.setValorVenda((double) tabelaVendas.getModel().getValueAt(i, 3));
            venda.add(v);
        }
        FormularioRecibo fr = new FormularioRecibo(venda);
        fr.setVisible(true);
    }//GEN-LAST:event_btVendaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCarrinho;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btVenda;
    private javax.swing.JLabel jCliente;
    private javax.swing.JComboBox<String> jComboCliente;
    private javax.swing.JComboBox<String> jComboProduto;
    private javax.swing.JLabel jListaCompras;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTbusca;
    private javax.swing.JTable tabelaProdutos2;
    private javax.swing.JTable tabelaVendas;
    // End of variables declaration//GEN-END:variables
}
