/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Gusta
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
    initComponents();
    setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE); 

    addWindowListener(new WindowAdapter() {
        @Override
        public void windowClosing(WindowEvent e) {
            int option = JOptionPane.showConfirmDialog(null, "Deseja realmente fechar o sistema?", "Confirmação", JOptionPane.YES_NO_OPTION);
            
            if (option == JOptionPane.YES_OPTION) {
                dispose(); 
            }
        }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AreaPrincipal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuClientes = new javax.swing.JMenuItem();
        jMenuFornecedores = new javax.swing.JMenuItem();
        jMenuProdutos = new javax.swing.JMenuItem();
        jMenuVenda = new javax.swing.JMenuItem();
        jMenuBuscar = new javax.swing.JMenu();
        jMenuProcurarFornecedor = new javax.swing.JMenuItem();
        jMenuProcurarCliente = new javax.swing.JMenuItem();
        jMenuProcurarProduto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 153));
        setSize(new java.awt.Dimension(1920, 1080));

        AreaPrincipal.setBackground(new java.awt.Color(255, 255, 204));
        AreaPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        AreaPrincipal.setAlignmentX(0.0F);
        AreaPrincipal.setAlignmentY(0.0F);
        AreaPrincipal.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/frango1.png"))); // NOI18N

        AreaPrincipal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout AreaPrincipalLayout = new javax.swing.GroupLayout(AreaPrincipal);
        AreaPrincipal.setLayout(AreaPrincipalLayout);
        AreaPrincipalLayout.setHorizontalGroup(
            AreaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AreaPrincipalLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel1)
                .addContainerGap(219, Short.MAX_VALUE))
        );
        AreaPrincipalLayout.setVerticalGroup(
            AreaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AreaPrincipalLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 153));
        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

        jMenuCadastro.setBackground(new java.awt.Color(0, 0, 0));
        jMenuCadastro.setForeground(new java.awt.Color(0, 0, 0));
        jMenuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/agenda32-icon.png"))); // NOI18N
        jMenuCadastro.setText("Cadastros");
        jMenuCadastro.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jMenuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroActionPerformed(evt);
            }
        });

        jMenuClientes.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jMenuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/cliente-icon.png"))); // NOI18N
        jMenuClientes.setText("Cliente");
        jMenuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClientesActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuClientes);

        jMenuFornecedores.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jMenuFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/cliente-icon.png"))); // NOI18N
        jMenuFornecedores.setText("Fornecedores");
        jMenuFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFornecedoresActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuFornecedores);

        jMenuProdutos.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jMenuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/beer.png"))); // NOI18N
        jMenuProdutos.setText("Produtos");
        jMenuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProdutosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuProdutos);

        jMenuVenda.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jMenuVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/relatorioTrabalho-icon.png"))); // NOI18N
        jMenuVenda.setText("Venda");
        jMenuVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVendaActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuVenda);

        jMenuBar1.add(jMenuCadastro);

        jMenuBuscar.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBuscar.setForeground(new java.awt.Color(0, 0, 0));
        jMenuBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/usuario32-icon.png"))); // NOI18N
        jMenuBuscar.setText("Buscar");
        jMenuBuscar.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N

        jMenuProcurarFornecedor.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jMenuProcurarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/relatorioTrabalho-icon.png"))); // NOI18N
        jMenuProcurarFornecedor.setText("Fornecedor");
        jMenuProcurarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProcurarFornecedorActionPerformed(evt);
            }
        });
        jMenuBuscar.add(jMenuProcurarFornecedor);

        jMenuProcurarCliente.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jMenuProcurarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/venda.png"))); // NOI18N
        jMenuProcurarCliente.setText("Cliente");
        jMenuProcurarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProcurarClienteActionPerformed(evt);
            }
        });
        jMenuBuscar.add(jMenuProcurarCliente);

        jMenuProcurarProduto.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jMenuProcurarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/beer.png"))); // NOI18N
        jMenuProcurarProduto.setText("Produto");
        jMenuProcurarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProcurarProdutoActionPerformed(evt);
            }
        });
        jMenuBuscar.add(jMenuProcurarProduto);

        jMenuBar1.add(jMenuBuscar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AreaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 945, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AreaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuProcurarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProcurarClienteActionPerformed
  FormularioBuscarClientes buscaClientes = new FormularioBuscarClientes();
        AreaPrincipal.add(buscaClientes);
        buscaClientes.setVisible(true);
    }//GEN-LAST:event_jMenuProcurarClienteActionPerformed

    private void jMenuProcurarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProcurarFornecedorActionPerformed
   FormularioBuscarFornecedor buscaFornecedores = new FormularioBuscarFornecedor();
   AreaPrincipal.add(buscaFornecedores);
   buscaFornecedores.setVisible(true);
    }//GEN-LAST:event_jMenuProcurarFornecedorActionPerformed

    private void jMenuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClientesActionPerformed
        FormularioCliente telaCadCliente = new FormularioCliente();
        AreaPrincipal.add(telaCadCliente);
        telaCadCliente.setVisible(true);   
    }//GEN-LAST:event_jMenuClientesActionPerformed

    private void jMenuFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFornecedoresActionPerformed
     FormularioFornecedor telaCadFornecedor = new FormularioFornecedor();
        AreaPrincipal.add(telaCadFornecedor);
     telaCadFornecedor.setVisible(true);
    }//GEN-LAST:event_jMenuFornecedoresActionPerformed

    private void jMenuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProdutosActionPerformed
    FormularioProduto telaCadProduto = new FormularioProduto();
        AreaPrincipal.add(telaCadProduto);
        telaCadProduto.setVisible(true);    }//GEN-LAST:event_jMenuProdutosActionPerformed

    private void jMenuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroActionPerformed
            }//GEN-LAST:event_jMenuCadastroActionPerformed

    private void jMenuProcurarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProcurarProdutoActionPerformed
    FormularioBuscarProduto buscaProdutos = new FormularioBuscarProduto();
        AreaPrincipal.add(buscaProdutos);
        buscaProdutos.setVisible(true);
    }//GEN-LAST:event_jMenuProcurarProdutoActionPerformed

    private void jMenuVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVendaActionPerformed
       FormularioVendas cadastrarVendas = new FormularioVendas();
        AreaPrincipal.add(cadastrarVendas);
        cadastrarVendas.setVisible(true);
    }//GEN-LAST:event_jMenuVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane AreaPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuBuscar;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuClientes;
    private javax.swing.JMenuItem jMenuFornecedores;
    private javax.swing.JMenuItem jMenuProcurarCliente;
    private javax.swing.JMenuItem jMenuProcurarFornecedor;
    private javax.swing.JMenuItem jMenuProcurarProduto;
    private javax.swing.JMenuItem jMenuProdutos;
    private javax.swing.JMenuItem jMenuVenda;
    // End of variables declaration//GEN-END:variables
}
